"""empty message

Revision ID: 8c748d99d453
Revises: f9ab1ca03db0
Create Date: 2023-05-09 12:00:59.842863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c748d99d453'
down_revision = 'f9ab1ca03db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('num_moons', sa.Integer(), nullable=True))
    op.drop_column('planet', 'moons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('moons', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('planet', 'num_moons')
    # ### end Alembic commands ###
